# syntax=docker/dockerfile:1
# Ayam Secrets Web build: removing tar steps, updating VAULT_VERSION

FROM node:24-trixie AS build
RUN node --version && npm --version

# Using https://github.com/ayamsecure/secrets-web-source/commits/v2026.7.0-ayam, always use commit hash
ARG VAULT_VERSION=0158e6c3725b6d1da7f3b6c92edba1302f5683aa
ENV VAULT_VERSION=$VAULT_VERSION
ENV VAULT_FOLDER=bw_clients
ENV CHECKOUT_TAGS=false

RUN mkdir /bw_web_builds
WORKDIR /bw_web_builds

COPY scripts ./scripts
# Use a glob pattern here so builds will continue even if the `.build_env` does not exists
COPY .build_env* ./

RUN ./scripts/checkout_web_vault.sh
RUN ./scripts/build_web_vault.sh
RUN mv "${VAULT_FOLDER}/apps/web/build" ./web-vault

# RUN tar -czvf "bw_web_vault.tar.gz" web-vault --owner=0 --group=0
# Output the sha256sum here so people are able to match the sha256sum from the CI with the assets and the downloaded version if needed
# RUN echo "sha256sum: $(sha256sum bw_web_vault.tar.gz)"

# We copy the final result as a separate empty image so there's no need to download all the intermediate steps
# The result is included both uncompressed and as a tar.gz, to be able to use it in the docker images and the github releases directly
FROM scratch
# hadolint ignore=DL3010
# COPY --from=build /bw_web_builds/bw_web_vault.tar.gz /bw_web_vault.tar.gz
COPY --from=build /bw_web_builds/web-vault /web-vault

# Added so docker create works, can't actually run a scratch image
CMD [""]